import { VoiceOptionProps } from '@/types/elevenlabs';

export const curatedVoices: VoiceOptionProps[] = [
  {
    label: 'Alice',
    value: 'Xb7hH8MSUJpSbSDYk0k2',
    gender: 'female',
    age: 'middle-aged',
    accent: 'british',
    description: 'confident',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/Xb7hH8MSUJpSbSDYk0k2/d10f7534-11f6-41fe-a012-2de1e482d336.mp3',
  },
  {
    label: 'Android',
    value: 'nPijfmaNgvm5OSN4xM8H',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'robotic',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/nPijfmaNgvm5OSN4xM8H/R27u5P6l8CJNtLpaC6fF.mp3',
  },
  {
    label: 'Aria',
    value: '9BWtsMINqrJLrRacOk9x',
    gender: 'female',
    age: 'middle-aged',
    accent: 'american',
    description: 'expressive',
    useCase: 'social media',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/9BWtsMINqrJLrRacOk9x/405766b8-1f4e-4d3c-aba1-6f25333823ec.mp3',
  },
  {
    label: 'Bill',
    value: 'pqHfZKP75CvOlQylNhV4',
    gender: 'male',
    age: 'old',
    accent: 'american',
    description: 'trustworthy',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/pqHfZKP75CvOlQylNhV4/d782b3ff-84ba-4029-848c-acf01285524d.mp3',
  },
  {
    label: 'Brian',
    value: 'nPczCjzI2devNBz1zQrb',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'deep',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/nPczCjzI2devNBz1zQrb/2dd3e72c-4fd3-42f1-93ea-abc5d4e5aa1d.mp3',
  },
  {
    label: 'Callum',
    value: 'N2lVS1w4EtoT3dr4eOWO',
    gender: 'male',
    age: 'middle-aged',
    accent: 'transatlantic',
    description: 'intense',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/N2lVS1w4EtoT3dr4eOWO/ac833bd8-ffda-4938-9ebc-b0f99ca25481.mp3',
  },
  {
    label: 'Carmen',
    value: 'eVItLK1UvXctxuaRV2Oq',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'seductive',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/eVItLK1UvXctxuaRV2Oq/CHtqtnSGvzxCBQyDa6m9.mp3',
  },
  {
    label: 'Charlie',
    value: 'IKne3meq5aSn9XLyUdCD',
    gender: 'male',
    age: 'middle-aged',
    accent: 'australian',
    description: 'natural',
    useCase: 'conversational',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/IKne3meq5aSn9XLyUdCD/102de6f2-22ed-43e0-a1f1-111fa75c5481.mp3',
  },
  {
    label: 'Charlotte',
    value: 'XB0fDUnXU5powFXDhCwa',
    gender: 'female',
    age: 'young',
    accent: 'swedish',
    description: 'seductive',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/XB0fDUnXU5powFXDhCwa/942356dc-f10d-4d89-bda5-4f8505ee038b.mp3',
  },
  {
    label: 'Chris',
    value: 'iP95p4xoKVk53GoZ742B',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'casual',
    useCase: 'conversational',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/iP95p4xoKVk53GoZ742B/3f4bde72-cc48-40dd-829f-57fbf906f4d7.mp3',
  },
  {
    label: 'Daniel',
    value: 'onwK4e9ZLuTAKqWW03F9',
    gender: 'male',
    age: 'middle-aged',
    accent: 'british',
    description: 'authoritative',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/onwK4e9ZLuTAKqWW03F9/7eee0236-1a72-4b86-b303-5dcadc007ba9.mp3',
  },
  {
    label: 'Demon',
    value: 'vfaqCOvlrKi4Zp7C2IAm',
    gender: 'male',
    age: 'middle-aged',
    accent: 'evil',
    description: 'demonic',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/vfaqCOvlrKi4Zp7C2IAm/mLg8Cp6Jq1r0xAbqjgwJ.mp3',
  },
  {
    label: 'Donny',
    value: 'QLwAEwhXGS7XYUmoD1vr',
    gender: 'male',
    age: 'old',
    accent: 'british',
    description: 'deep',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/UwDtqCF44YaL77wxb8DVQlHT5Gp1/voices/pf6xPPiM5R4VK6VnUM4f/72c7532f-3545-4d99-b4a1-35b6f791f1c9.mp3',
  },
  {
    label: 'Dr. Doktor',
    value: 'Mg1264PmwVoIedxsF9nu',
    gender: 'male',
    age: 'middle-aged',
    accent: 'scientist',
    description: 'anxious',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/P6pUmq42X5NZv0RV97gQ0XrmuXL2/voices/Mg1264PmwVoIedxsF9nu/02538d3a-f225-445a-bb58-4983e74cc609.mp3',
  },
  {
    label: 'Eastend Steve',
    value: '1TE7ou3jyxHsyRehUuMB',
    gender: 'male',
    age: 'middle-aged',
    accent: 'british',
    description: 'friendly',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/1TE7ou3jyxHsyRehUuMB/EHjTRjsNYkFb7uHD2asA.mp3',
  },
  {
    label: 'Eric',
    value: 'cjVigY5qzO86Huf0OWal',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'friendly',
    useCase: 'conversational',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/cjVigY5qzO86Huf0OWal/d098fda0-6456-4030-b3d8-63aa048c9070.mp3',
  },
  {
    label: 'George',
    value: 'JBFqnCBsd6RMkjVDRZzb',
    gender: 'male',
    age: 'middle-aged',
    accent: 'british',
    description: 'warm',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/JBFqnCBsd6RMkjVDRZzb/e6206d1a-0721-4787-aafb-06a6e705cac5.mp3',
  },

  {
    label: 'Harrison',
    value: 'repzAAjoKlgcT2oOAIWt',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'corporate',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/NZbzesqA6CUDRU2CXJenhD5MeIu1/voices/repzAAjoKlgcT2oOAIWt/db6f7bb5-6bac-4de7-8c79-728d66ee90fe.mp3',
  },
  {
    label: 'Hope',
    value: 'tnSpp4vdxKPjI9w0GnoV',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'corporate',
    useCase: 'social media',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/tnSpp4vdxKPjI9w0GnoV/LiIyxRT1qFJ1QJPr8sWl.mp3',
  },
  {
    label: 'Howard',
    value: 'NFG5qt843uXKj4pFvR7C',
    gender: 'male',
    age: 'middle-aged',
    accent: 'british',
    description: 'relaxed',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/NFG5qt843uXKj4pFvR7C/BgPFcmyMBm88O9O05Myn.mp3',
  },
  {
    label: 'Ivy',
    value: 'a0euEDMIIr9cUObJf0DX',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'cute',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/database/user/glklRmLoFeWZciiTRthKn6JAIwp1/voices/a0euEDMIIr9cUObJf0DX/J6VVJe6zZJRQICk3EgVh.mp3',
  },
  {
    label: 'Jessica',
    value: 'cgSgspJ2msm6clMCkdW9',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'expressive',
    useCase: 'conversational',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/cgSgspJ2msm6clMCkdW9/56a97bf8-b69b-448f-846c-c3a11683d45a.mp3',
  },
  {
    label: 'Jonah',
    value: 'Ny7JIsE1mP4WjUTvqSqI',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'sassy',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/26I8rRbYppUyfjBXYwc7Wlgq3o62/voices/m1l6XE6QWs5I9FuWKeUQ/e10d1399-bdf0-4011-9593-36e4a663ee52.mp3',
  },
  {
    label: 'Khemet',
    value: 'tSFL3SkkI7qDAnuiY5Vt',
    gender: 'male',
    age: 'old',
    accent: 'african',
    description: 'deep',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/lA5gT7FFPLVt66XJyVjpVR1ljPA2/voices/oTHQYfn7DWnTG0ar27wr/87da670b-5140-4d30-8587-d9ed07f1d99d.mp3',
  },
  {
    label: 'Lily',
    value: 'pFZP5JQG7iQjIQuC4Bku',
    gender: 'female',
    age: 'middle-aged',
    accent: 'british',
    description: 'warm',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/pFZP5JQG7iQjIQuC4Bku/89b68b35-b3dd-4348-a84a-a3c13a3c2b30.mp3',
  },
  {
    label: 'Marcus',
    value: 'AtpeQBi3Ck7KyUH0CKap',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'deep',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/EjqRMuZ2nrZL47hTwNm1fCCtcgi2/voices/TJdGgFoRwIpDGaLZCRzq/a527f950-d34b-4bd1-9ce7-c995ea69fda3.mp3',
  },
  {
    label: 'Matilda',
    value: 'XrExE9yKIg1WjnnlVkGX',
    gender: 'female',
    age: 'middle-aged',
    accent: 'american',
    description: 'friendly',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/XrExE9yKIg1WjnnlVkGX/b930e18d-6b4d-466e-bab2-0ae97c6d8535.mp3',
  },

  {
    label: 'Morganna',
    value: '7NsaqHdLuKNFvEfjpUno',
    gender: 'female',
    age: 'old',
    accent: 'witch',
    description: 'wise',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/7NsaqHdLuKNFvEfjpUno/LyhT6nxqgbsw2z56SfVt.mp3',
  },

  {
    label: 'Natasha',
    value: 'knPuaBAZCIymA4r1SjIR',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'sassy',
    useCase: 'social media',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/CpJRF07XekXZp2RcBTTkntmWfi72/voices/uxKr2vlA4hYgXZR1oPRT/b987a4d1-e94c-44ea-b42c-b40785a8e590.mp3',
  },
  {
    label: 'Oxley',
    value: '2gPFXx8pN3Avh27Dw5Ma',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'deep',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/2gPFXx8pN3Avh27Dw5Ma/GcxfxoMG5hz8u6uLX9TP.mp3',
  },
  {
    label: 'Roger',
    value: 'CwhRBWXzGAHq8TQ4Fs17',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'confident',
    useCase: 'social media',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/CwhRBWXzGAHq8TQ4Fs17/58ee3ff5-f6f2-4628-93b8-e38eb31806b0.mp3',
  },
  {
    label: 'Santa Claus',
    value: 'Gqe8GJJLg3haJkTwYj2L',
    gender: 'male',
    age: 'old',
    accent: 'american',
    description: 'jolly',
    useCase: 'characters_animation',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/Gqe8GJJLg3haJkTwYj2L/sS7onTCoIlPiDTWIFgdK.mp3',
  },
  {
    label: 'Sarah',
    value: 'EXAVITQu4vr4xnSDxMaL',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'soft',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/EXAVITQu4vr4xnSDxMaL/01a3e33c-6e99-4ee7-8543-ff2216a32186.mp3',
  },
  {
    label: 'Timmy',
    value: 'chcMmmtY1cmQh2ye1oXi',
    gender: 'male',
    age: 'young',
    accent: 'british',
    description: 'energetic',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/custom/voices/chcMmmtY1cmQh2ye1oXi/mdBV0XLS9541mA6h7u7N.mp3',
  },
];
