import { VoiceOptionProps } from '@/types/elevenlabs';

export const elevenLabsVoices: VoiceOptionProps[] = [
  {
    label: 'Adam',
    value: 'pNInz6obpgDQGcFmaJgB',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'deep',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/pNInz6obpgDQGcFmaJgB/d6905d7a-dd26-4187-bfff-1bd3a5ea7cac.mp3',
  },
  {
    label: 'Alice',
    value: 'Xb7hH8MSUJpSbSDYk0k2',
    gender: 'female',
    age: 'middle-aged',
    accent: 'british',
    description: 'confident',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/Xb7hH8MSUJpSbSDYk0k2/d10f7534-11f6-41fe-a012-2de1e482d336.mp3',
  },
  {
    label: 'Antoni',
    value: 'ErXwobaYiN019PkySvjV',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'well-rounded',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/ErXwobaYiN019PkySvjV/2d5ab2a3-4578-470f-b797-6331e46a7d55.mp3',
  },
  {
    label: 'Arnold',
    value: 'VR6AewLTigWG4xSOukaG',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'crisp',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/VR6AewLTigWG4xSOukaG/49a22885-80d5-48e8-87a3-076fc9193d9a.mp3',
  },
  {
    label: 'Bill',
    value: 'pqHfZKP75CvOlQylNhV4',
    gender: 'male',
    age: 'old',
    accent: 'american',
    description: 'trustworthy',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/pqHfZKP75CvOlQylNhV4/d782b3ff-84ba-4029-848c-acf01285524d.mp3',
  },
  {
    label: 'Brian',
    value: 'nPczCjzI2devNBz1zQrb',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'deep',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/nPczCjzI2devNBz1zQrb/2dd3e72c-4fd3-42f1-93ea-abc5d4e5aa1d.mp3',
  },
  {
    label: 'Callum',
    value: 'N2lVS1w4EtoT3dr4eOWO',
    gender: 'male',
    age: 'middle-aged',
    accent: 'transatlantic',
    description: 'intense',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/N2lVS1w4EtoT3dr4eOWO/ac833bd8-ffda-4938-9ebc-b0f99ca25481.mp3',
  },
  {
    label: 'Charlie',
    value: 'IKne3meq5aSn9XLyUdCD',
    gender: 'male',
    age: 'middle-aged',
    accent: 'australian',
    description: 'natural',
    useCase: 'conversational',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/IKne3meq5aSn9XLyUdCD/102de6f2-22ed-43e0-a1f1-111fa75c5481.mp3',
  },
  {
    label: 'Charlotte',
    value: 'XB0fDUnXU5powFXDhCwa',
    gender: 'female',
    age: 'young',
    accent: 'swedish',
    description: 'seductive',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/XB0fDUnXU5powFXDhCwa/942356dc-f10d-4d89-bda5-4f8505ee038b.mp3',
  },
  {
    label: 'Chris',
    value: 'iP95p4xoKVk53GoZ742B',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'casual',
    useCase: 'conversational',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/iP95p4xoKVk53GoZ742B/3f4bde72-cc48-40dd-829f-57fbf906f4d7.mp3',
  },
  {
    label: 'Clyde',
    value: '2EiwWnXFnvU5JabPnv8n',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'war veteran',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/2EiwWnXFnvU5JabPnv8n/65d80f52-703f-4cae-a91d-75d4e200ed02.mp3',
  },
  {
    label: 'Daniel',
    value: 'onwK4e9ZLuTAKqWW03F9',
    gender: 'male',
    age: 'middle-aged',
    accent: 'british',
    description: 'authoritative',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/onwK4e9ZLuTAKqWW03F9/7eee0236-1a72-4b86-b303-5dcadc007ba9.mp3',
  },
  {
    label: 'Dave',
    value: 'CYw3kZ02Hs0563khs1Fj',
    gender: 'male',
    age: 'young',
    accent: 'british',
    description: 'conversational',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/CYw3kZ02Hs0563khs1Fj/872cb056-45d3-419e-b5c6-de2b387a93a0.mp3',
  },
  {
    label: 'Domi',
    value: 'AZnzlk1XvdvUeBnXmlld',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'strong',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/AZnzlk1XvdvUeBnXmlld/b3c36b01-f80d-4b16-a698-f83682dee84c.mp3',
  },
  {
    label: 'Dorothy',
    value: 'ThT5KcBeYPX3keUQqHPh',
    gender: 'female',
    age: 'young',
    accent: 'british',
    description: 'pleasant',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/ThT5KcBeYPX3keUQqHPh/981f0855-6598-48d2-9f8f-b6d92fbbe3fc.mp3',
  },
  {
    label: 'Drew',
    value: '29vD33N1CtxCmqQRPOHJ',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'well-rounded',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/29vD33N1CtxCmqQRPOHJ/b99fc51d-12d3-4312-b480-a8a45a7d51ef.mp3',
  },
  {
    label: 'Elli',
    value: 'MF3mGyEYCl7XYWbV9V6O',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'emotional',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/MF3mGyEYCl7XYWbV9V6O/d8ecadea-9e48-4e5d-868a-2ec3d7397861.mp3',
  },
  {
    label: 'Emily',
    value: 'LcfcDJNUP1GQjkzn1xUU',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'calm',
    useCase: 'meditation',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/LcfcDJNUP1GQjkzn1xUU/e4b994b7-9713-4238-84f3-add8fccaaccd.mp3',
  },
  {
    label: 'Eric',
    value: 'cjVigY5qzO86Huf0OWal',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'friendly',
    useCase: 'conversational',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/cjVigY5qzO86Huf0OWal/d098fda0-6456-4030-b3d8-63aa048c9070.mp3',
  },
  {
    label: 'Ethan',
    value: 'g5CIjZEefAph4nQFvHAz',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'soft',
    useCase: 'asmr',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/g5CIjZEefAph4nQFvHAz/26acfa99-fdec-43b8-b2ee-e49e75a3ac16.mp3',
  },
  {
    label: 'Fin',
    value: 'D38z5RcWu1voky8WS1ja',
    gender: 'male',
    age: 'old',
    accent: 'irish',
    description: 'sailor',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/D38z5RcWu1voky8WS1ja/a470ba64-1e72-46d9-ba9d-030c4155e2d2.mp3',
  },
  {
    label: 'Freya',
    value: 'jsCqWAovK2LkecY7zXl4',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'expressive',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/jsCqWAovK2LkecY7zXl4/8e1f5240-556e-4fd5-892c-25df9ea3b593.mp3',
  },
  {
    label: 'George',
    value: 'JBFqnCBsd6RMkjVDRZzb',
    gender: 'male',
    age: 'middle-aged',
    accent: 'british',
    description: 'warm',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/JBFqnCBsd6RMkjVDRZzb/e6206d1a-0721-4787-aafb-06a6e705cac5.mp3',
  },
  {
    label: 'Gigi',
    value: 'jBpfuIE2acCO8z3wKNLl',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'childlish',
    useCase: 'animation',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/jBpfuIE2acCO8z3wKNLl/3a7e4339-78fa-404e-8d10-c3ef5587935b.mp3',
  },
  {
    label: 'Giovanni',
    value: 'zcAOhNBS3c14rBihAFp1',
    gender: 'male',
    age: 'young',
    accent: 'italian',
    description: 'foreigner',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/zcAOhNBS3c14rBihAFp1/e7410f8f-4913-4cb8-8907-784abee5aff8.mp3',
  },
  {
    label: 'Glinda',
    value: 'z9fAnlkpzviPz146aGWa',
    gender: 'female',
    age: 'middle-aged',
    accent: 'american',
    description: 'witch',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/z9fAnlkpzviPz146aGWa/cbc60443-7b61-4ebb-b8e1-5c03237ea01d.mp3',
  },
  {
    label: 'Grace',
    value: 'oWAxZDx7w5VEj9dCyTzz',
    gender: 'female',
    age: 'young',
    accent: 'american (south)',
    description: 'pleasant',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/oWAxZDx7w5VEj9dCyTzz/84a36d1c-e182-41a8-8c55-dbdd15cd6e72.mp3',
  },
  {
    label: 'Harry',
    value: 'SOYHLrjzK2X1ezoPC6cr',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'anxious',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/SOYHLrjzK2X1ezoPC6cr/86d178f6-f4b6-4e0e-85be-3de19f490794.mp3',
  },
  {
    label: 'James',
    value: 'ZQe5CZNOzWyzPSCn5a3c',
    gender: 'male',
    age: 'old',
    accent: 'australian',
    description: 'calm',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/ZQe5CZNOzWyzPSCn5a3c/35734112-7b72-48df-bc2f-64d5ab2f791b.mp3',
  },
  {
    label: 'Jeremy',
    value: 'bVMeCyTHy58xNoL34h3p',
    gender: 'male',
    age: 'young',
    accent: 'irish',
    description: 'excited',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/bVMeCyTHy58xNoL34h3p/66c47d58-26fd-4b30-8a06-07952116a72c.mp3',
  },
  {
    label: 'Jessica',
    value: 'cgSgspJ2msm6clMCkdW9',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'expressive',
    useCase: 'conversational',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/cgSgspJ2msm6clMCkdW9/56a97bf8-b69b-448f-846c-c3a11683d45a.mp3',
  },
  {
    label: 'Jessie',
    value: 't0jbNlBVZ17f02VDIeMI',
    gender: 'male',
    age: 'old',
    accent: 'american',
    description: 'raspy',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/t0jbNlBVZ17f02VDIeMI/e26939e3-61a4-4872-a41d-33922cfbdcdc.mp3',
  },
  {
    label: 'Joseph',
    value: 'Zlb1dXrM653N07WRdFW3',
    gender: 'male',
    age: 'middle-aged',
    accent: 'british',
    description: 'articulate',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/Zlb1dXrM653N07WRdFW3/daa22039-8b09-4c65-b59f-c79c48646a72.mp3',
  },
  {
    label: 'Josh',
    value: 'TxGEqnHWrfWFTfGW9XjX',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'deep',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/TxGEqnHWrfWFTfGW9XjX/47de9a7e-773a-42a8-b410-4aa90c581216.mp3',
  },
  {
    label: 'Laura',
    value: 'FGY2WhTYpPnrIDTdsKH5',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'upbeat',
    useCase: 'social media',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/FGY2WhTYpPnrIDTdsKH5/67341759-ad08-41a5-be6e-de12fe448618.mp3',
  },
  {
    label: 'Liam',
    value: 'TX3LPaxmHKxFdv7VOQHJ',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'articulate',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/TX3LPaxmHKxFdv7VOQHJ/63148076-6363-42db-aea8-31424308b92c.mp3',
  },
  {
    label: 'Lily',
    value: 'pFZP5JQG7iQjIQuC4Bku',
    gender: 'female',
    age: 'middle-aged',
    accent: 'british',
    description: 'warm',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/pFZP5JQG7iQjIQuC4Bku/89b68b35-b3dd-4348-a84a-a3c13a3c2b30.mp3',
  },
  {
    label: 'Matilda',
    value: 'XrExE9yKIg1WjnnlVkGX',
    gender: 'female',
    age: 'middle-aged',
    accent: 'american',
    description: 'friendly',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/XrExE9yKIg1WjnnlVkGX/b930e18d-6b4d-466e-bab2-0ae97c6d8535.mp3',
  },
  {
    label: 'Michael',
    value: 'flq6f7yk4E4fJM5XTYuZ',
    gender: 'male',
    age: 'old',
    accent: 'american',
    description: 'calm',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/flq6f7yk4E4fJM5XTYuZ/c6431a82-f7d2-4905-b8a4-a631960633d6.mp3',
  },
  {
    label: 'Mimi',
    value: 'zrHiDhphv9ZnVXBqCLjz',
    gender: 'female',
    age: 'young',
    accent: 'swedish',
    description: 'childish',
    useCase: 'animation',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/zrHiDhphv9ZnVXBqCLjz/decbf20b-0f57-4fac-985b-a4f0290ebfc4.mp3',
  },
  {
    label: 'Nicole',
    value: 'piTKgcLEGmPE4e6mEKli',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'soft',
    useCase: 'asmr',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/piTKgcLEGmPE4e6mEKli/c269a54a-e2bc-44d0-bb46-4ed2666d6340.mp3',
  },
  {
    label: 'Patrick',
    value: 'ODq5zmih8GrVes37Dizd',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'shouty',
    useCase: 'characters',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/ODq5zmih8GrVes37Dizd/0ebec87a-2569-4976-9ea5-0170854411a9.mp3',
  },
  {
    label: 'Paul',
    value: '5Q0t7uMcjvnagumLfvZi',
    gender: 'male',
    age: 'middle-aged',
    accent: 'american',
    description: 'authoritative',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/5Q0t7uMcjvnagumLfvZi/a4aaa30e-54c4-44a4-8e46-b9b00505d963.mp3',
  },
  {
    label: 'Rachel',
    value: '21m00Tcm4TlvDq8ikWAM',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'calm',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/21m00Tcm4TlvDq8ikWAM/b4928a68-c03b-411f-8533-3d5c299fd451.mp3',
  },
  {
    label: 'Sam',
    value: 'yoZ06aMxZJJ28mfd3POQ',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'raspy',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/yoZ06aMxZJJ28mfd3POQ/b017ad02-8d18-4456-ad92-55c85ecf6363.mp3',
  },
  {
    label: 'Sarah',
    value: 'EXAVITQu4vr4xnSDxMaL',
    gender: 'female',
    age: 'young',
    accent: 'american',
    description: 'soft',
    useCase: 'news',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/EXAVITQu4vr4xnSDxMaL/01a3e33c-6e99-4ee7-8543-ff2216a32186.mp3',
  },
  {
    label: 'Serena',
    value: 'pMsXgVXv3BLzUgSXRplE',
    gender: 'female',
    age: 'middle-aged',
    accent: 'american',
    description: 'pleasant',
    useCase: 'narration',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/pMsXgVXv3BLzUgSXRplE/d61f18ed-e5b0-4d0b-a33c-5c6e7e33b053.mp3',
  },
  {
    label: 'Thomas',
    value: 'GBv7mTt0atIp3Br8iCZE',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'calm',
    useCase: 'meditation',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/GBv7mTt0atIp3Br8iCZE/98542988-5267-4148-9a9e-baa8c4f14644.mp3',
  },
  {
    label: 'Will',
    value: 'bIHbv24MWmeRgasZH58o',
    gender: 'male',
    age: 'young',
    accent: 'american',
    description: 'friendly',
    useCase: 'social media',
    sampleURL:
      'https://storage.googleapis.com/eleven-public-prod/premade/voices/bIHbv24MWmeRgasZH58o/8caf8f3d-ad29-4980-af41-53f20c72d7a4.mp3',
  },
];
